# Generated by Django 5.2.5 on 2025-08-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('fat_name', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('stu_class', models.CharField(max_length=100)),
                ('fees', models.PositiveIntegerField()),
            ],
        ),
    ]
