# Generated by Django 5.2.5 on 2025-08-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_route', models.CharField(max_length=100)),
                ('stu_fees', models.PositiveIntegerField()),
            ],
        ),
    ]
