# Generated by Django 5.2.5 on 2025-08-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_routedetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transport',
            new_name='TransportDetail',
        ),
    ]
